### ISSUE TITLE
Can provider Image Color(RGB) infomation ? 

### ISSUE THREAD

**Issue by CMingTseng** [Ashampoo/kim#102]
Dear Sir 

very thx this project 

i study "Steganography" need "RGB" infomation 

i want a middle object get Image (  Java :  BufferedImage / Android:Bitmap /iOS : ? )

THX

**Comment by StefanOltmann** [comment]
Hello,

Kim is for working with image metadata.

What you are looking for is [Skiko](https://github.com/JetBrains/skiko), a Kotlin multiplatform SKIA wrapper.

Kind regards,

Stefan
