### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by mipastgt** [Ashampoo/kim#41]
Are you planning to support the new WASM target in the near future? I am just evaluating the feasibility of converting my current project to a WASM browser project.

**Comment by StefanOltmann** [comment]
I will look into that. :)

**Comment by StefanOltmann** [comment]
@mipastgt I tried incorporating the targets `wasmJs` and `wasmWasi` to evaluate the present situation.

It seems that Ktor currently lacks support for WASM. Kim depends on Ktor tools for the `Charset` class and multiplatform `String`.

Consequently, I am confronted with the decision of either waiting for Ktor to introduce WASM support or exploring alternative solutions for multiplatform `String` and `Charset`.

While Ashampoo Photos doesn't currently require WASM, I'm open to supporting as many platforms as possible to enhance the utility of this library.

**Comment by mipastgt** [comment]
I am depending on Ktor myself too, so there is no need to hurry. There are also a lot more libraries that I depend on which are not yet available with WASM support.

**Comment by StefanOltmann** [comment]
In the process of integrating WebAssembly support for the Ashampoo XMP Core dependency, I've identified the need for enabling WASM support in xmlutil as well. You can track the progress and related discussions on this issue at: [xmlutil GitHub Issue #157](https://github.com/pdvrieze/xmlutil/issues/157).

Although the implementation may take some time, once it becomes generally available, I plan to incorporate WASM support accordingly.

**Comment by mipastgt** [comment]
In the end you will also need full image processing capabilities for WASM but maybe this https://github.com/korlibs/korge/pull/2057 is interesting in this context.

**Comment by StefanOltmann** [comment]
@mipastgt Most of it has been implemented and released in v0.8 now, but PNG support is limited due to a missing WASM zlib implementation (#45).

**Comment by StefanOltmann** [comment]
Available in v0.8.1
