### ISSUE TITLE
Version 0.9.2 as used in the Readme does not exist

### ISSUE THREAD

**Issue by mipastgt** [Ashampoo/kim#58]
In the Readme file you advertise version 0.9.2 (see: https://github.com/Ashampoo/kim#installation) but exactly this version does not exist on maven. (See: https://mvnrepository.com/artifact/com.ashampoo/kim) Only versions 0.9.1 and 0.9.3 exist. Took me a while to figure out why my build failed.

**Comment by StefanOltmann** [comment]
Thank you for pointing that out. I’m sorry for the inconvenience.

**Comment by StefanOltmann** [comment]
Fixed.
