### ISSUE TITLE
Missing support for iosX64

### ISSUE THREAD

**Issue by mipastgt** [Ashampoo/kim#77]
Hi,
when I try to build a new project of mine I get the following error.
```
Execution failed for task ':apptools:apptools-core:transformCommonMainDependenciesMetadata'.
> Could not resolve all files for configuration ':apptools:apptools-core:iosX64CompilationDependenciesMetadata'.
   > Could not resolve com.ashampoo:kim:0.13.
     Required by:
```
In contrast to my other projects this one is also intended to run on iOS. That's probably the reason why I did not notice this before. This target is needed to run on the simulator on X64 macOS hardware.

**Comment by mipastgt** [comment]
Seems to work with latest version 0.15.1. I still had an older one in my setup.

**Comment by StefanOltmann** [comment]
Yes, I added it alongside with linux support in `v0.15`. :)
